### ISSUE TITLE
Adicionar configuração de continuar transação sem 3DS

### ISSUE THREAD

**Issue by emanuellopess** [LinkNacional/wc_cielo_payment_gateway#107]
Cliente quer uma opção de caso de falha com o 3DS a transação siga sem a autenticação 3DS, essa opção de ignorar autenticação 3DS e seguir com a transação deve estar desabilitada por padrão

**Comment by souzadavi** [comment]
Verificar se é possível identificar se o cartão é ou não elegível para o 3DS antes de cobrar. A ideia é evitar que apareça uma mensagem de alert na tela para o usuário.

Se não for possível, verificar se podemos alterar o texto da mensagem de cartão não elegível.

Confirmar se a funcionalidade é compatível com Cartões de Débito.
