### ISSUE TITLE
Ajustar label de código de segurança

### ISSUE THREAD

**Issue by emanuellopess** [LinkNacional/wc_cielo_payment_gateway#22]
Talvez alterar o label para Cód. Segurança

![image](https://github.com/LinkNacional/wc_cielo_payment_gateway/assets/74307223/c4cd7013-184b-4b9f-8518-b46171413536)

**Comment by helonfranca02** [comment]
Ajuste realizado modificando alguns elementos no HTML e CSS, e renomeando a etiqueta do código de segurança para "CVV".
