### ISSUE TITLE
Cartão de débito desativado 

### ISSUE THREAD

**Issue by souzadavi** [LinkNacional/wc_cielo_payment_gateway#34]
Quando o cartão de débito estiver desabilitado o mesmo não deve carregar no checkout do woocmmerce para evitar... 

Ou seja, atualmente mesmo que o cartão de débito esteja desabilitado nas configurações de gateway de pagamento do woocommerce o JS é carregado no checkout do woocomerce... 

Solução: não carregar o JS do 3DS no checkout do woocommerce quando o mesmo não estiver configurado e habilitado.

**Comment by helonfranca02** [comment]
- [ ] Testar no plugin de faturas: [woocommerce-invoice-payment](https://github.com/LinkNacional/woocommerce-invoice-payment).
