### ISSUE TITLE
Mostrar informações de parcela na descrição do produto

### ISSUE THREAD

**Issue by souzadavi** [LinkNacional/wc_cielo_payment_gateway#35]
O plugin ter opção de um shortcode ou adição automática no qual o usuário pode adicionar informações sobre o valor quando pago parcelado o produto.

Exemplo: 
![image](https://github.com/LinkNacional/wc_cielo_payment_gateway/assets/636225/1fd23241-c839-482f-86e2-258a6ad050ca)

**Comment by emanuellopess** [comment]
@souzadavi  Não faz sentindo um plugin de pagamento alterar página de produtos, foge do escopo estabelecido pelo WooCommerce. O parcelamento é calculado a partir do valor total do carrinho na página de finalizar compras, há plugins próprios que fazem a customização da página de produtos e mostram a opção de parcelamento.

Podemos por essa ideia e juntar com algumas outras e fazer um plugin próprio com customizações da área de produtos.
