### ISSUE TITLE
Adicionar compatibilidade com block-based checkout

### ISSUE THREAD

**Issue by emanuellopess** [LinkNacional/wc_cielo_payment_gateway#39]
Adicionar compatibilidade com checkout em blocos para woocommerce

![image](https://github.com/LinkNacional/wc_cielo_payment_gateway/assets/74307223/1e46b626-c750-48c5-b3b2-bf02825bd433)

**Comment by souzadavi** [comment]
Informações sobre: 
https://woo.com/document/cart-checkout-blocks-status/

**Comment by helonfranca02** [comment]
Para solucionar o problema das formas de pagamento não aparecendo, fiz uma alteração na página de checkout. Removi todo o conteúdo existente e substituí por "[woocommerce_checkout]" dentro de um bloco. Isso resultou na criação de um novo formulário com as formas de pagamento funcionando corretamente. Essa foi uma solução que me permitiu resolver os outros problemas que estavam nas issues.
