### ISSUE TITLE
Adicionar botão "Seja pro" 

### ISSUE THREAD

**Issue by emanuellopess** [LinkNacional/wc_cielo_payment_gateway#44]
Adicionar botão seja pro na listagem de plugins, [link do botão](https://www.linknacional.com.br/wordpress/woocommerce/cielo/)

![image](https://github.com/LinkNacional/wc_cielo_payment_gateway/assets/74307223/b1fc4cc6-1b35-4f9d-848f-6895b4e0a536)

**Comment by helonfranca02** [comment]
Concluído!
