### ISSUE TITLE
Adição de tratamento de erros melhorado no sistema de consulta de token 3DS

### ISSUE THREAD

**Issue by emanuellopess** [LinkNacional/wc_cielo_payment_gateway#45]
Caso o sistema de consulta de token do Cielo 3DS apresente alguma falha é necessário que salvemos mais logs, utilize o try...catch também na função de gerar token para evitar erros críticos. Verificar caso [desse cliente](https://wordpress.org/support/topic/critico-uncaught-exception-geracao-de-token-de-atutenticacao-falhou/)

**Comment by helonfranca02** [comment]
Concluído!
