### ISSUE TITLE
Verificar sistema de consulta de bandeiras Cielo

### ISSUE THREAD

**Issue by emanuellopess** [LinkNacional/wc_cielo_payment_gateway#46]
Função de consultar bandeira de cartão de crédito apresenta alguns erros, porém eles não são facilmente identificáveis, necessário adicionar mais logs e verificar se função está funcionando corretamente para todas as bandeiras, verificar se validação com regex ainda é válida

[Caso 1](https://wordpress.org/support/topic/retorno-da-cielo/)
[Caso 2](https://wordpress.org/support/topic/estou-recebendo-reclamacoes-todo-mes-de-problemas-com-cartao/)

**Comment by helonfranca02** [comment]
Concluido!
