### ISSUE TITLE
Adicionar campos de credenciais de cartão de débito e crédito obrigatório

### ISSUE THREAD

**Issue by emanuellopess** [LinkNacional/wc_cielo_payment_gateway#47]
Adicionar atributo required em todos os campos de credenciais da página de configurações dos métodos de pagamento Cielo crédito e débito

![image](https://github.com/LinkNacional/wc_cielo_payment_gateway/assets/74307223/c31e0036-20fe-4841-9b45-c938c799b467)

**Comment by helonfranca02** [comment]
Concluído!
