### ISSUE TITLE
Verificar funcionamento com cupom de desconto e frete

### ISSUE THREAD

**Issue by emanuellopess** [LinkNacional/wc_cielo_payment_gateway#72]
Adicionar verificação do cielo 3DS para pagamentos com desconto e com cálculo de frete:

- [x] Testar 3DS em caso de mudança de valores no front-end;
- [x] Verificar formulário 3.0.0

**Comment by emanuellopess** [comment]
@GuilhermeLinkNacional Cliente relata que ao adicionar novos produtos ao carrinho não atualiza os valores do parcelamento:

<img width="998" alt="Captura_de_Tela_2024-09-11_as_14 47 32" src="https://github.com/user-attachments/assets/4e1ee71d-d691-45d0-b1e1-50567f778563">

Necessário adicionar calculo das parcelas nos eventos de carregamento do carrinho de compras, acredito que seja isso, o cliente não informou o plugin e tema utilizados para adicionar produtos ao carrinho de compras na tela de finalização de compra

**Comment by GuilhermeLinkNacional** [comment]
Corrigido
