### ISSUE TITLE
Verificar carregamento de script 3DS

### ISSUE THREAD

**Issue by emanuellopess** [LinkNacional/wc_cielo_payment_gateway#85]
Cliente relata que ao habilitar o plugin o servidor faz diversas requisições ao mpi.braspag, necessário validar como o script do 3DS está sendo carregado e talvez adicionar verificações adicionais. Necessário checar se requisição para gerar token não está sendo realizada sem o 3DS estar habilitado.

**Comment by GuilhermeLinkNacional** [comment]
Feito no PR #87
