### ISSUE TITLE
Ativar modo compatibilidade para placeholders

### ISSUE THREAD

**Issue by emanuellopess** [LinkNacional/wc_cielo_payment_gateway#92]
Clientes alegam que o placeholder não está aparecendo acredito que podemos criar uma configuração de compatibilidade para melhorar a apresentação em temas que não permitam placeholders

- [x] Criar configuração de modo de compatibilidade de placeholder
- [x] Ao habilitar todos os nossos campos precisam adicionar os atributos plceholder e data-placeholder Ex.:
```html
<input id="lkn_cc_cvc" name="lkn_cc_cvc" type="tel" inputmode="numeric" class="lkn-cvv" maxlength="8" required="" placeholder="xxx" data-placeholder="xxx">
```
- [x] O placeholder deve seguir o padrão definido no script de máscaras:

```js
$('.lkn-cvv').mask('000')
$('.lkn-card-exp').mask('00 / 00')
$('.lkn-card-num').mask('0000000000000000')
```

**Comment by emanuellopess** [comment]
@GuilhermeLinkNacional Alterar valor dos palceholders para os da imagem:

![image](https://github.com/user-attachments/assets/d44a1130-747a-459f-93c5-e98922871a68)


Tem uma configuração que habilita os placeholders nos formulários de checkout via shortcode só precisa alterar por lá

**Comment by GuilhermeLinkNacional** [comment]
Alterado
